### ISSUE TITLE
[Feature]: Developp a mini-game which use concentration rate and record a demo

### ISSUE THREAD

**Issue by mvallenet** [PoCInnovation/MindGame#18]
### Description

You have to developp a mini-game which use concentration rate.
After that, you have to record a demo which shows the operation.

### Expected behaviour

The team have to:
- [x] Developp a mini-game in free langage
- [x] Use the concentration rate in input of a neural network
- [x] Make the game attractive to the eye
- [x] Record a demo which shows the operation

### Environment

- OS and version

### Proposed solution

/

**Comment by Baragouin** [comment]
@agherasie c'est déjà fait ça c'est bon ? il faut juste faire la démo et faire le hot-record ?

**Comment by agherasie** [comment]
> @agherasie c'est déjà fait ça c'est bon ? il faut juste faire la démo et faire le hot-record ?

"Make the game attractive to the eye" c'est pas fait que ce soit au niveau du code ou le jeu en lui même mais sinon *en principe* oui
