### ISSUE TITLE
[Feature]: try to use tanh instead of ReLu in NN

### ISSUE THREAD

**Issue by mvallenet** [PoCInnovation/MindGame#20]
### Description

NN training seem's to not work randomly.
Try to use tanh instead of ReLu in NN.

### Expected behaviour

Training should works at every time.

### Environment

/

### Proposed solution

/

**Comment by agherasie** [comment]
`tanh` works great ! I've tried it a couple dozen times since yesterday and it consistently reaches ~98% accuracy @Mikatech

**Comment by mvallenet** [comment]
@agherasie nice work !
