### ISSUE TITLE
[Feature]: Implement DVC & connect it to a bucket S3

### ISSUE THREAD

**Issue by mvallenet** [PoCInnovation/MindGame#9]
### Description

The goal of this task is to implement a DVC connected to a bucket S3

### Expected behaviour

The team have to:
- [x] Initialise a DVC
- [x] Ask me for a API key for the bucket
- [x] Connect the DVC to the bucket

### Environment

/

### Proposed solution

/

**Comment by Baragouin** [comment]
@Mikatech Should we setup DVC locally or on the MindGame repo?

**Comment by Baragouin** [comment]
I initialized DVC on this branch: #11
